// workspaces/apps/vite/react/src/components/Button.tsx
import "@cartok/todo-list-styles/components/Button.css";
import clsx from "clsx";
import mergeProps from "merge-props";
import { type JSX } from "react";
import { type ParentElementProps, type ValidElementAttributes } from "~/types";

type ValidElements = keyof Pick<
  JSX.IntrinsicElements,
  "button" | "a" | "div" | "span"
>;

type ButtonProps = {
  size?: "default" | "double" | "hug";
};

export function Button<T extends ValidElements>(
  props: ParentElementProps<T, ButtonProps>
) {
  const defaultProps: Partial<ButtonProps> = {
    size: "default",
  };

  const defaultElementProps: {
    [K in ValidElements]?: ValidElementAttributes<K>;
  } = {
    button: {
      type: "button",
    },
  };

  props = mergeProps(defaultProps, defaultElementProps, props);

  const Element = props.element.tag;

  return (
    <Element
      className={clsx("button", {
        [props.size as string]: true,
      })}
      {...props.element.attributes}
    >
      {props.children}
    </Element>
  );
}

// solid/src/components/Button.tsx
import {
  type JSX,
  type ParentProps,
  children as getMemorizedChildren,
} from "solid-js";
import { Dynamic } from "solid-js/web";
// TODO: aliased imports, maybe setup monorepo.
import "./Button.css";
import type { DynamicHTMLElementProps } from "../types";

export function Button<T extends keyof JSX.IntrinsicElements = "button">(
  props: ParentProps<
    DynamicHTMLElementProps<T> & {
      size?: "default" | "double" | "hug";
    }
  >
) {
  props = { element: "button" as T, size: "default", ...props };

  const memorizedChildren = getMemorizedChildren(() => props.children);

  return (
    <Dynamic
      classList={{ button: true, [props.size as string]: true }}
      component={props.element as string}
      {...props.attributes}
    >
      {memorizedChildren()}
    </Dynamic>
  );
}
