// workspaces/apps/vite/react/src/components/TodoList.tsx
import "@cartok/todo-list-styles/components/TodoList.css";
import { useState, type FormEvent } from "react";
import { Button } from "~/components/Button";
import { TextInputControlled } from "~/components/TextInput";
import { todoListStore } from "~/components/TodoList.store";
import { TodoListFormItem } from "~/components/TodoListItem";

export function TodoList() {
  const [text, setText] = useState<string>("");

  // TODO: use callback
  function submitAddToList(event: FormEvent) {
    event.preventDefault();

    if (!text) {
      return;
    }

    todoListStore.actions.addToList(text);
  }

  return (
    <div className="todo-list">
      <form className="form" onSubmit={submitAddToList}>
        <TextInputControlled value={text} setValue={setText} />
        <Button element={{ tag: "button", attributes: { type: "submit" } }}>
          add
        </Button>
      </form>
      <ul className="list">
        <For each={todoListStore.items()}>
          {([id, item]) => (
            <TodoListFormItem id={id}>{item.text}</TodoListFormItem>
          )}
        </For>
      </ul>
    </div>
  );
}

// solid/src/components/TodoList.tsx
import { createEffect, createSignal, For } from "solid-js";
import { Button } from "./Button";
import "./TodoList.css";
import { todoListStore } from "./TodoList.store";
import { TodoListItem } from "./TodoListItem";

export function TodoList() {
  const [text, setText] = createSignal<string>("");

  function addToList(event: Event) {
    event.preventDefault();

    if (!text()) {
      return;
    }

    todoListStore.actions.addToList(text());
  }

  createEffect(() => {
    console.log("text:", text());
    console.log("list:", todoListStore.data);
  });

  return (
    // TODO: Mal gucken wie mit scoped element selectors aussehen würde.
    // Man könnte sich halt abstraktion sparen und nur nutzen wenn es nötig ist bzw.
    // wenn ein tag mehr als einmal vorkommt und dabei mindestens zwei verschiedene
    // UI elemente rendert.
    <div class="todo-list">
      <form class="form" onSubmit={addToList}>
        {/* TODO: Also try out input binding in the frameworks */}
        {/* <TextInput> */}
        <input
          value={text()}
          onInput={(e) => setText(e.target.value)}
          style={{
            "background-color": "red",
          }}
        />
        {/* WIP: checking some limits & patterns */}
        <Button attributes={{ type: "submit" }}>add</Button>
      </form>
      <ol class="list">
        <For each={Array.from(todoListStore.data.items)}>
          {([id, item]) => <TodoListItem id={id}>{item.text}</TodoListItem>}
        </For>
      </ol>
    </div>
  );
}
