// workspaces/apps/vite/solid/src/components/Button.tsx
import { type JSX, createMemo, mergeProps } from "solid-js";
import type { ParentElementProps, ValidElementAttributes } from "~/types";
import "./Button.css";

type ValidElements = keyof Pick<
  JSX.IntrinsicElements,
  "button" | "a" | "div" | "span"
>;

type ButtonProps = {
  size?: "default" | "double" | "hug";
};

export function Button<T extends ValidElements>(
  props: ParentElementProps<T, ButtonProps>
) {
  const defaultProps: Partial<ButtonProps> = {
    size: "default",
  };

  const defaultElementProps: {
    [K in ValidElements]?: ValidElementAttributes<K>;
  } = {
    button: {
      type: "button",
    },
  };

  const Element = createMemo<string>(() => props.element.tag);
  const mergedProps = mergeProps(defaultProps, defaultElementProps, props);

  // TODO: finish basic component
  // TODO: aria

  return (
    <Element
      classList={{
        button: true,
        [mergedProps.size as string]: true,
      }}
      component={props.element.tag}
      {...mergedProps.element.attributes}
    >
      {mergedProps.children}
    </Element>
  );
}

function TEST() {
  return (
    <Button element={{ tag: "button", attributes: { type: "" } }}>sdf</Button>
  );
}

// workspaces/apps/vite/react/src/components/Button.tsx
import "@cartok/todo-list-styles/components/Button.css";
import clsx from "clsx";
import mergeProps from "merge-props";
import { type JSX } from "react";
import { type ParentElementProps, type ValidElementAttributes } from "~/types";

type ValidElements = keyof Pick<
  JSX.IntrinsicElements,
  "button" | "a" | "div" | "span"
>;

type ButtonProps = {
  size?: "default" | "double" | "hug";
};

export function Button<T extends ValidElements>(
  props: ParentElementProps<T, ButtonProps>
) {
  const defaultProps: Partial<ButtonProps> = {
    size: "default",
  };

  const defaultElementProps: {
    [K in ValidElements]?: ValidElementAttributes<K>;
  } = {
    button: {
      type: "button",
    },
  };

  props = mergeProps(defaultProps, defaultElementProps, props);

  const Element = props.element.tag;

  return (
    <Element
      className={clsx("button", {
        [props.size as string]: true,
      })}
      {...props.element.attributes}
    >
      {props.children}
    </Element>
  );
}
