// workspaces/apps/vite/react/src/components/Header.tsx
import "@cartok/todo-list-styles/components/Header.css";
import type { PropsWithChildren } from "react";

export function Header(props: PropsWithChildren) {
  return (
    <header className="header">
      <h1 className="title">TODO List</h1>
      <h4 className="framework">(in {props.children})</h4>
    </header>
  );
}

// workspaces/apps/vite/solid/src/components/Header.tsx
import { children, type ParentComponent } from "solid-js";
import "./Header.css";

export const Header: ParentComponent = (props) => {
  const resolvedChildren = children(() => props.children);

  return (
    <header class="header">
      <h1 class="title">TODO List</h1>
      <div class="framework">(in {resolvedChildren()})</div>
    </header>
  );
};
