// workspaces/apps/vite/react/src/components/Header.tsx
import "@cartok/todo-list-styles/components/Header.css";
import type { PropsWithChildren } from "react";

export function Header(props: PropsWithChildren) {
  return (
    <header className="header">
      <h1 className="title">TODO List</h1>
      <h4 className="framework">(in {props.children})</h4>
    </header>
  );
}

// workspaces/frontends/vite/solidjs/src/components/Header.tsx
import "@cartok/todo-list-styles/components/Header.css";
import { children, type ParentProps } from "solid-js";

export function Header(props: ParentProps) {
  const resolvedChildren = children(() => props.children);

  return (
    <header class="header">
      <h1 class="title">TODO List</h1>
      <h4 class="framework">(in {resolvedChildren()})</h4>
    </header>
  );
}
